### ISSUE TITLE
conflicts with other packages 

### ISSUE THREAD

**Issue by MarcoderPM** [turlvo/flutter_headset_detector#6]
I am making an app using following packagess: just_audio, flutter_phoenix and  google_fonts
they are not compatible, because flutter_headset_detector needs minsdk 24 and then the other packages do not work.
I need a solution a.s.a.p.

**Comment by turlvo** [comment]
@MarcoderPM 
I'm sorry for the inconvenience.
Please check it as 3.1.0.
